import type { LucideProps } from 'lucide-react';
import {
  LayoutDashboard,
  Users,
  CalendarClock,
  FileText,
  Briefcase,
  Settings,
  LogOut,
  ChevronDown,
  ChevronRight,
  Menu,
  Bell,
  Sun,
  Moon,
  UserCircle,
  FileBarChart,
  Building,
  DollarSign,
  Plane,
  CheckSquare,
  Clock3,
  Landmark,
  X,
  TrendingUp,
  ClipboardCheck,
  BookOpen,
  ShieldCheck,
  Files,
  PlusCircle,
  Download,
  HeartPulse,
  CreditCard,
  ClipboardList,
  Laptop,
  Network,
  Gift,
  BarChart3,
  HelpCircle,
  Megaphone,
  Share2,
  Copy,
  Sparkles,
  Brain,
  Phone,
  MessageSquare,
  AlertTriangle,
  LifeBuoy,
  Vegan,
  Stethoscope,
  CalendarDays,
  Bed,
  Calculator,
  GraduationCap,
  Clock,
  Hourglass,
  PowerOff,
  Headphones,
  ShieldAlert,
  Bot,
  Award,
  Table,
  ChevronLeft,
  LogIn,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Users: Users,
  PaymentSchedule: CalendarClock,
  TaxManagement: FileText,
  Briefcase: Briefcase,
  Settings: Settings,
  Logout: LogOut,
  Login: LogIn,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft, 
  Menu: Menu,
  Bell: Bell,
  Sun: Sun,
  Moon: Moon,
  UserCircle: UserCircle,
  Reports: FileBarChart,
  Company: Building,
  Payroll: DollarSign,
  Leave: Plane,
  Applicants: CheckSquare,
  TimeLog: Clock3,
  Bank: Landmark,
  CloseIcon: X,
  TrendingUp: TrendingUp,
  ClipboardCheck: ClipboardCheck,
  BookOpen: BookOpen,
  ShieldCheck: ShieldCheck,
  Files: Files,
  PlusCircle: PlusCircle,
  Download: Download,
  Wellness: HeartPulse,
  ExpenseManagement: CreditCard,
  Surveys: ClipboardList,
  AssetManagement: Laptop,
  OrgChart: Network,
  Gift: Gift,
  Analytics: BarChart3,
  HelpCircle: HelpCircle,
  Megaphone: Megaphone,
  Share: Share2,
  Copy: Copy,
  Sparkles: Sparkles,
  Brain: Brain,
  Phone: Phone,
  MessageSquare: MessageSquare,
  AlertTriangle: AlertTriangle,
  LifeBuoy: LifeBuoy,
  Vegan: Vegan,
  Stethoscope: Stethoscope,
  CalendarDays: CalendarDays,
  Bed: Bed,
  Calculator: Calculator,
  GraduationCap: GraduationCap,
  Clock: Clock,
  Hourglass: Hourglass,
  PowerOff: PowerOff,
  Headphones: Headphones,
  ShieldAlert: ShieldAlert,
  Bot: Bot,
  Award: Award,
  ListChecks: CheckSquare,
  Table: Table,
  CalendarClock: CalendarClock,
};

export type Icon = keyof typeof Icons;
